from .layout_cleaning import CLEANING, DETECTION_RESULTS, USER_LABELING, CLEANING_TABS, UILTAGS
from .layout_profiling import DATA_PROFILE, FD_MODAL
from .layout_datashets import LOAD_DATA_SHEET, DATA_SHEET
from .layout_upload_data import NAVBAR, UPLOAD, LOAD_SQL
from .layout_dataset import DATA_QUALITY, DATASET

layouts = {
   "NAVBAR": NAVBAR,
    "UPLOAD": UPLOAD,
    "LOAD_SQL": LOAD_SQL,
    "CLEANING": CLEANING,
    "DATASET": DATASET,
    "USER_LABELING": USER_LABELING,
    "UILTAGS": UILTAGS,
    "DATA_QUALITY": DATA_QUALITY,
    "DATA_PROFILE": DATA_PROFILE,
    "FD_MODAL": FD_MODAL,
    "DETECTION_RESULTS": DETECTION_RESULTS,
    "LOAD_DATA_SHEET": LOAD_DATA_SHEET,
    "DATA_SHEET": DATA_SHEET,
    'CLEANING_TABS': CLEANING_TABS
}